site:
  title: BYU OIT AV // Docs
  url: https://docs.avs.byu.edu
  start_page: docs::index.adoc
content:
  sources:
    - url: https://github.com/byuoitav/docs.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"
